/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    usuarios: UsuarioAuthOperations;
  };
  blocks: {};
  collections: {
    representadas: Representada;
    pecas: Peca;
    arquivos3d: Arquivos3D;
    acabamentos: Acabamento;
    projetos: Projeto;
    paginas: Pagina;
    imagens: Imagen;
    logotipos: Logotipo;
    arquivos: Arquivo;
    leads: Lead;
    usuarios: Usuario;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    representadas: RepresentadasSelect<false> | RepresentadasSelect<true>;
    pecas: PecasSelect<false> | PecasSelect<true>;
    arquivos3d: Arquivos3DSelect<false> | Arquivos3DSelect<true>;
    acabamentos: AcabamentosSelect<false> | AcabamentosSelect<true>;
    projetos: ProjetosSelect<false> | ProjetosSelect<true>;
    paginas: PaginasSelect<false> | PaginasSelect<true>;
    imagens: ImagensSelect<false> | ImagensSelect<true>;
    logotipos: LogotiposSelect<false> | LogotiposSelect<true>;
    arquivos: ArquivosSelect<false> | ArquivosSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    usuarios: UsuariosSelect<false> | UsuariosSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    empresa: Empresa;
    home: Home;
    'quem-somos': QuemSomos;
    prancha: Prancha;
    'pacote-3d': Pacote3D;
  };
  globalsSelect: {
    empresa: EmpresaSelect<false> | EmpresaSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    'quem-somos': QuemSomosSelect<false> | QuemSomosSelect<true>;
    prancha: PranchaSelect<false> | PranchaSelect<true>;
    'pacote-3d': Pacote3DSelect<false> | Pacote3DSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Usuario;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UsuarioAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * As fábricas que a Belmare representa. Cada uma tem uma página no site, e essa página mostra só o que a fábrica de fato declara — o que não existe fica ausente, sem "em breve" e sem espaço em branco.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "representadas".
 */
export interface Representada {
  id: number;
  /**
   * Como a fábrica se chama, escrito como ela mesma escreve — "Marê Mobília", "GDA Móveis". É o título da página dela no site.
   */
  nome: string;
  /**
   * O fim do endereço da página: com "trisol" aqui, a página fica em belmare.com.br/representadas/trisol. Só letras minúsculas sem acento, números e hífen. Depois que a página estiver no ar, mudar isto quebra todo link que já foi enviado. ⚠️ Só uma conta administradora grava este campo — o Payload mostra o valor a quem for operador, mas mantém o campo travado para leitura.
   */
  slug: string;
  /**
   * Em que ordem esta marca aparece na galeria da home e nas listas do site. Menor vem primeiro. Deixe em branco e ela vai para o fim.
   */
  ordem?: number | null;
  /**
   * A linha desta fábrica, como se escreve numa lista de representadas — "Ombrelones laterais e centrais", "Estofados com têxtil de performance", "Mobiliário em alumínio fundido". Com inicial maiúscula e sem ponto final: o site põe o ponto onde precisa. Nomeie produto e matéria, nunca benefício — "a sombra" e "o conforto" dizem o que o cliente sente, e o arquiteto especifica o que a fábrica faz.
   */
  resolve: string;
  /**
   * A palavra que a seta da prancha aponta e que legenda a galeria — "Sombra", "Estrutura", "Estofado". Tem que ser algo que se enxerga na fotografia: duas setas escritas "conforto" e "móvel" sobre dois estofados não ensinam nada.
   */
  parte: string;
  /**
   * Onde a fábrica fica, no formato "Cambé · PR". Deixe em branco se a fábrica não publica isso em lugar nenhum — a página escreve "Origem não declarada" com todas as letras, e é melhor do que um chute que o leitor desta página repara.
   */
  base?: string | null;
  /**
   * Um dado que qualquer um pode conferir na fonte da própria fábrica — "Ferragem em inox 304, resistência a vento de 30 a 80 km/h". Sem superlativo e sem adjetivo: "a melhor", "referência no mercado" e "alta qualidade" não são fatos e derrubam a autoridade de tudo o mais que a página diz.
   */
  fato: string;
  /**
   * A marca da fábrica, do jeito que ela mesma desenhou. Prefira o SVG; PNG só com fundo transparente e pelo menos o dobro do tamanho que aparece na tela. O site publica o arquivo como ele é — não recolore nem recorta —, então peça à fábrica o vetor original e a autorização de uso. Sem arquivo, a marca simplesmente não aparece e o cartão começa pela fotografia.
   */
  logotipo?: (number | null) | Logotipo;
  /**
   * A imagem que representa esta marca na galeria da home e nos registros de /representadas. Mostre a linha da fábrica — não uma peça do catálogo dela, que o site não tem autorização para apresentar como acervo.
   */
  imagem: number | Imagen;
  /**
   * A imagem larga que abre a página desta marca, sangrando de ponta a ponta. Precisa ser OUTRA fotografia, e num enquadramento panorâmico: é a mesma marca vista de outro jeito, não a foto da galeria em tamanho maior.
   */
  imagemLarga: number | Imagen;
  /**
   * A ficha técnica nas palavras da própria fábrica: matéria, prazo, garantia, ambiente. Só o que ela publica — não complete a lista de uma marca para igualar a de outra, porque a autoridade desta seção é o leitor poder conferir cada linha na fonte.
   */
  declaracoes?:
    | {
        /**
         * O que está sendo declarado, em uma ou duas palavras — "Matéria", "Prazo", "Vento".
         */
        rotulo: string;
        /**
         * O que a fábrica declara, como ela declara — "De 30 a 80 km/h, conforme o modelo". Faixa continua faixa: quebrar em número por modelo dá uma tabela mais bonita e inventada.
         */
        valor: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Os designers que assinam para esta fábrica, quando ela publica os nomes. É o que separa marca de autor de fabricante genérico, e é o que o arquiteto usa para defender a escolha dele. Nome e coleção, e nada além: retrato e biografia são de terceiros e não são nossos para publicar.
   */
  designers?:
    | {
        /**
         * O nome como a fábrica o publica, incluindo estúdio — "Estúdio Galho".
         */
        nome: string;
        /**
         * Só onde a própria fábrica liga o designer à coleção. A GDA publica os designers e publica as coleções, mas não diz quem assinou o quê — nesse caso deixe vazio, porque adivinhar por afinidade é palpite com cara de ficha técnica. As coleções sem atribuição vão no campo "Coleções da fábrica", mais abaixo.
         */
        colecoes?: string[] | null;
        /**
         * Uma linha curta que a fábrica publica sobre o designer — "Estúdio interno". Deixe em branco se ela não publica nada.
         */
        nota?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * As coleções que a fábrica publica sem dizer quem as assinou. Elas aparecem na seção de vocabulário, sem atribuição — que é onde de fato pertencem. Se a fábrica atribui cada coleção a um designer, use o campo de coleções dentro de "Quem assina" e deixe este vazio.
   */
  colecoes?: string[] | null;
  /**
   * As categorias de produto nas palavras desta fábrica. O site não normaliza vocabulário entre marcas: cada uma usa as suas, e o filtro nunca sai da marca. Uma fábrica que ainda não declarou taxonomia fica sem esta seção e as outras vão ao ar sem esperar por ela.
   */
  vocabulario?: {
    /**
     * Como a fábrica divide o catálogo dela antes de chegar na categoria: a GDA separa por ambiente, a Trisol por tipo de haste. É a presença deste eixo que decide se a página oferece um filtro de categoria. Sem eixo é uma lista só, e uma lista só não se filtra.
     */
    eixo?: string | null;
    /**
     * Um grupo por valor do eixo — "Externo" e "Interno" na GDA. Sem eixo declarado, use um grupo só com todas as categorias dentro.
     */
    grupos?:
      | {
          /**
           * Como a fábrica chama este recorte — "Laterais", "Centrais", "Externo".
           */
          nome: string;
          /**
           * O que entra na barra do navegador quando o visitante filtrar por este grupo: "laterais", "area-externa". Só letras minúsculas sem acento, números e hífen.
           */
          slug: string;
          /**
           * As categorias deste grupo, uma por linha, nas palavras da fábrica. Um grupo sem nenhuma categoria não aparece na página — não vira título vazio.
           */
          itens?:
            | {
                /**
                 * O nome da categoria como a fábrica a chama — "Espreguiçadeiras", "Bistrô", "Vitta".
                 */
                nome: string;
                /**
                 * Uma distinção que a fábrica publica sobre esta categoria — "Comercial, resiste a 80 km/h". Só onde ela publica: deduzir a diferença pelo nome é inventar especificação.
                 */
                nota?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Os catálogos desta fábrica, um por PDF — pode ser um só ou um por coleção. Cada linha precisa do arquivo anexado: o site lista o que dá para baixar, e nada além disso. Uma linha sem PDF não aparece em /catalogos nem na página da marca, e não vira "em breve" — enquanto o arquivo não chegar, quem pede o catálogo pede pelo WhatsApp, no botão que já existe no fim da página.
   */
  catalogos?:
    | {
        /**
         * Como o documento se chama, e é ele que separa um catálogo dos outros desta mesma fábrica — "Catálogo geral", "Linha Ânima", "Área externa". Com um catálogo só, "Catálogo" basta. Não escreva a edição aqui: o ano tem campo próprio logo abaixo e o site compõe a linha sozinho.
         */
        titulo: string;
        /**
         * O ano da edição, só quando a fábrica o declara. Em branco, a página escreve "Edição não declarada" com todas as letras — que é o certo. Um 2025 plausível inventado aqui é o site mentindo sobre a única coisa que o arquiteto usa para saber se o documento está velho.
         */
        ano?: number | null;
        /**
         * O arquivo em si. O peso aparece sozinho na página, lido do PDF — não há o que preencher e não há o que estimar. Sem ele esta linha não vai para o site: se o catálogo ainda não chegou da fábrica, apague a linha e cadastre-a no dia em que o arquivo chegar.
         */
        arquivo?: (number | null) | Arquivo;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * As marcas das fábricas representadas, como a própria fábrica as desenhou. O site publica o arquivo exatamente como ele sobe — não recolore, não recorta e não redesenha. Peça sempre o vetor e a autorização de uso junto.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logotipos".
 */
export interface Logotipo {
  id: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * As fotografias do site. Toda imagem precisa de descrição, e toda imagem que ainda não é fotografia real precisa estar marcada como referência.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imagens".
 */
export interface Imagen {
  id: number;
  /**
   * Descreva o que aparece na foto para quem não pode vê-la. Nomeie objetos e materiais — "poltrona de área externa trançada em corda" —, não a sensação. Não escreva "imagem de referência" aqui: se a imagem estiver marcada abaixo, o site acrescenta isso sozinho.
   */
  descricao: string;
  /**
   * Marque enquanto a imagem for geração ou foto de terceiro usada como exemplo. Com isso marcado, a descrição publicada termina em "imagem de referência". Desmarque no dia em que a fotografia real substituir esta — a marcação some sozinha de todos os lugares onde aparecia.
   */
  mock?: boolean | null;
  /**
   * O texto que o site realmente publica. É composto a partir dos dois campos acima e não pode ser editado aqui.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Os arquivos que o visitante baixa: catálogos em PDF e, mais adiante, os arquivos 3D. O peso e o formato são lidos do próprio arquivo — não há o que preencher.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "arquivos".
 */
export interface Arquivo {
  id: number;
  /**
   * Como este arquivo é chamado na página — "Catálogo Trisol 2026". É o texto que o visitante lê antes de decidir baixar.
   */
  titulo: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * As peças em destaque de cada representada. A categoria só aceita os termos que a própria fábrica já declarou no vocabulário dela — o filtro nunca atravessa para outra marca.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pecas".
 */
export interface Peca {
  id: number;
  /**
   * A fábrica a quem esta peça pertence. A categoria abaixo só aceita as palavras que ESTA fábrica já declarou no próprio vocabulário.
   */
  representada: number | Representada;
  /**
   * Como a peça se chama — "Jubarte", "Vitta", "Bistrô".
   */
  nome: string;
  /**
   * A categoria desta peça, EXATAMENTE como está escrita no vocabulário desta representada — "Espreguiçadeiras", "Vitta". Uma categoria nova só existe depois de cadastrada no vocabulário da própria fábrica, na página dela.
   */
  categoria: string;
  /**
   * A fotografia desta peça.
   */
  foto: number | Imagen;
  /**
   * Só quando a própria fábrica separa o catálogo por ambiente, como a GDA. Deixe em branco se a marca não faz essa distinção.
   */
  ambiente?: ('externo' | 'interno') | null;
  /**
   * Legenda descritiva e opcional — "Alumínio fundido e corda náutica". Texto livre, não uma lista fechada: não filtra, não navega e nunca vira parâmetro de URL. Se a fábrica não informou, deixe em branco — nada quebra.
   */
  materiais?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Os arquivos 3D de cada representada. Formato e peso aparecem sozinhos na página, lidos do próprio arquivo — não há o que preencher.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "arquivos3d".
 */
export interface Arquivos3D {
  id: number;
  /**
   * A fábrica a quem este arquivo 3D pertence.
   */
  representada: number | Representada;
  /**
   * Como este arquivo é chamado na página — "Cadeira Zuri". É o texto que o arquiteto lê antes de decidir baixar.
   */
  nome: string;
  /**
   * O arquivo em si — SketchUp, DWG, 3ds ou Revit. Formato e peso aparecem na página sozinhos, lidos deste arquivo.
   */
  arquivo: number | Arquivo;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Os tecidos e pinturas de cada representada, com amostra.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "acabamentos".
 */
export interface Acabamento {
  id: number;
  /**
   * A fábrica a quem este acabamento pertence.
   */
  representada: number | Representada;
  /**
   * Como a fábrica chama este acabamento — "Olefina Areia", "Grafite Texturizado".
   */
  nome: string;
  /**
   * Tecido ou pintura — não há um terceiro tipo hoje.
   */
  tipo: 'tecido' | 'pintura';
  /**
   * A fotografia de perto deste acabamento.
   */
  amostra: number | Imagen;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Obras entregues em que peças das representadas foram especificadas e instaladas. A seção só entra no ar em /quem-somos no dia em que houver três projetos publicados — dois leem como exceção, e a página fica de pé sem esta seção até lá. Antes de publicar qualquer projeto, confirme três consentimentos: o direito de uso da fotografia, a autorização do cliente final e o crédito do arquiteto (campo obrigatório, abaixo). Projeto residencial de alto padrão costuma ter cláusula de confidencialidade — confirme antes de publicar, não depois.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projetos".
 */
export interface Projeto {
  id: number;
  /**
   * Como a obra é nomeada publicamente — "Residência Costa", "Cobertura Beira-Mar". Nunca o endereço: cidade e estado, logo abaixo, bastam para localizar.
   */
  obra: string;
  /**
   * A cidade onde a obra foi entregue. Sem rua, sem número.
   */
  cidade: string;
  /**
   * A sigla do estado — "SC", "PR", "RS".
   */
  uf: string;
  /**
   * O ano em que a obra foi entregue.
   */
  ano: number;
  /**
   * Quais fábricas representadas pela Belmare foram DE FATO especificadas nesta obra — uma, duas ou as quatro. Não é lista de patrocínio: só quem entrou no projeto de verdade.
   */
  marcas: (number | Representada)[];
  /**
   * A fotografia da obra entregue. Nunca uma imagem de referência: se a foto escolhida estiver marcada como referência (mock) no acervo, a publicação deste projeto é recusada. Confirme o direito de uso da imagem e a autorização do cliente final antes de escolher.
   */
  foto: number | Imagen;
  /**
   * O escritório ou profissional responsável pelo projeto — "Estúdio Galho Arquitetura". Campo obrigatório: não é cortesia, é o que faz o multiplicador que enviou este projeto mandar o próximo.
   */
  creditoArquiteto: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * As três páginas montadas por blocos: Arquitetos, Contato e Política de privacidade. Escolha o endereço, escreva o título e monte a página arrastando blocos. As demais páginas do site têm sequência desenhada e não se montam aqui.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paginas".
 */
export interface Pagina {
  id: number;
  /**
   * Qual das páginas do site esta composição preenche. Só aparecem aqui os endereços que já existem — uma página nova exige uma rota nova, que é código. Cada endereço recebe uma composição só.
   */
  slug: 'arquitetos' | 'contato' | 'politica-de-privacidade';
  /**
   * O título grande que abre a página, e o nome dela na aba do navegador. ⚠️ Nomeie o que o visitante veio buscar, não o setor da empresa: "Catálogos, arquivos 3D e acabamentos" diz mais do que "Área do arquiteto".
   */
  titulo: string;
  /**
   * Uma ou duas frases descrevendo o que ESTÁ nesta página — é o texto que aparece no resultado de busca, a única superfície do site que se lê antes do site. ⚠️ Não prometa aqui o que a página não entrega: quem clica chega já desmentido.
   */
  resumo: string;
  /**
   * Os blocos desta página, na ordem em que aparecem. Arraste para reordenar — a pré-visualização ao lado acompanha. Quatro blocos, com papéis que não se sobrepõem: texto, caminhos, a ficha da Belmare e a faixa de WhatsApp.
   */
  composicao?: (BlocoDeProsa | BlocoDeCaminhos | BlocoDeFicha | BlocoDeFecho)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlocoDeProsa".
 */
export interface BlocoDeProsa {
  /**
   * O título que abre esta seção. Deixe em branco quando o texto continua a seção anterior — é o caso do primeiro parágrafo de quase toda página.
   */
  titulo?: string | null;
  /**
   * Parágrafos, subtítulos, listas e links. Bloco mal preenchido não vai ao ar: a página desenha um bloco a menos, nunca um bloco quebrado. ⚠️ Não escreva aqui o endereço, o telefone, o CNPJ nem o e-mail da Belmare: eles têm o bloco "Ficha da Belmare", que os lê do cadastro e nunca discorda dele. Redigitados aqui, envelhecem sem ninguém perceber.
   */
  corpo: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'prosa';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlocoDeCaminhos".
 */
export interface BlocoDeCaminhos {
  /**
   * O que a lista abaixo oferece — "Por onde seguir", "O que você precisa". Em branco, os caminhos aparecem direto.
   */
  titulo?: string | null;
  /**
   * Um caminho por escolha real. Bloco mal preenchido não vai ao ar: a página desenha um bloco a menos, nunca um bloco quebrado.
   */
  itens?:
    | {
        /**
         * Escrito na voz de quem lê, não na da empresa — "Quero comprar", "Baixar os catálogos". Um rótulo que descreve o setor da Belmare em vez do desejo do visitante não é uma escolha, é um organograma.
         */
        rotulo: string;
        /**
         * Uma linha dizendo o que acontece ao clicar. Em branco, o caminho fica só com o rótulo.
         */
        apoio?: string | null;
        destino: 'rota' | 'whatsapp' | 'formulario';
        /**
         * Só as páginas que já existem aparecem aqui. Uma rota que ainda não foi construída não é oferecida: um caminho para um 404 é pior do que caminho nenhum.
         */
        rota?:
          | (
              | '/representadas'
              | '/catalogos'
              | '/arquivos-3d'
              | '/quem-somos'
              | '/arquitetos'
              | '/contato'
              | '/politica-de-privacidade'
            )
          | null;
        /**
         * A mensagem chega no WhatsApp já escrita — "Oi! Vim pelo site: …". Escreva a continuação na primeira pessoa: "queria propor uma revenda", "queria os catálogos das representadas". É a única qualificação de lead que o site tem, e ela custa zero.
         */
        contexto?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'caminhos';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlocoDeFicha".
 */
export interface BlocoDeFicha {
  /**
   * Sobre a ficha — "Onde encontrar", "A empresa". Em branco, a ficha abre direto. ⚠️ Este é o único bloco sem conteúdo para preencher, e é de propósito: endereço, telefones, e-mail, Instagram, território e CNPJ saem do cadastro em "O site › A Belmare". Corrigir um telefone lá corrige aqui, no rodapé e em toda página que use esta ficha, de uma vez. O que estiver em branco no cadastro simplesmente não aparece.
   */
  titulo?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ficha';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlocoDeFecho".
 */
export interface BlocoDeFecho {
  /**
   * Em branco, escreve "Falar pelo WhatsApp". Troque quando a página pede algo mais específico — "Pedir os catálogos num pedido só".
   */
  rotulo?: string | null;
  /**
   * A continuação de "Oi! Vim pelo site: …", na primeira pessoa. ⚠️ Sem número de WhatsApp cadastrado a faixa inteira não é desenhada — um botão que é o elemento mais pesado da página e abre um contato inexistente é pior do que botão nenhum.
   */
  contexto: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'fecho';
}
/**
 * Os contatos recebidos pelo formulário do site — hoje só "Quero revender", em /contato. Todo lead chega aqui e, quando o e-mail comercial está cadastrado e o Resend está configurado, também por e-mail — mas esta lista é a cópia que sobrevive mesmo quando o e-mail falha ou nunca foi configurado.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  /**
   * Como a pessoa se identificou no formulário.
   */
  nome: string;
  /**
   * Para onde a Belmare responde.
   */
  email: string;
  /**
   * De onde a pessoa fala.
   */
  cidade: string;
  /**
   * A loja, o escritório de arquitetura ou a operação que a pessoa representa — o mínimo para a Belmare qualificar o contato (decisão 11 da spec). O mesmo campo serve os dois papéis: só o rótulo do formulário muda entre uma página de revenda e uma de arquiteto.
   */
  escritorio: string;
  /**
   * ⚠️ Separado do envio da mensagem, de propósito: marcar ou não isto nunca muda se o contato é recebido. O formulário do site nunca vem com esta caixa pré-marcada — ver `components/formulario-de-lead.tsx`. Contatar a empresa não é, e não pode virar, inscrição automática em lista nenhuma.
   */
  consentimentoMarketing?: boolean | null;
  /**
   * De onde este contato veio. O visitante não vê nem edita estes dois campos — eles chegam ocultos no envio, preenchidos pela própria página.
   */
  origem: {
    /**
     * O endereço de onde o formulário foi enviado — "contato", por exemplo.
     */
    pagina: string;
    /**
     * Qual representada, quando o formulário abrir a partir da página de uma marca (o seam que PRA-127 usa). Em branco nas páginas que não são de marca nenhuma, como /contato.
     */
    marca?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuarios".
 */
export interface Usuario {
  id: number;
  /**
   * Como você aparece no histórico de alterações. Nome e sobrenome bastam.
   */
  nome: string;
  /**
   * Operador é a Belmare: edita prosa, fotografia, catálogo, peça, projeto e a composição das páginas livres — o painel inteiro foi desenhado para este papel. Administrador é o desenvolvedor: além de tudo isso, é o único que cria e apaga representada e edita o endereço (slug) dela — mudar ou apagar URL é o tipo de engano que o operador não tem como ver vindo. Deixe em branco ao criar uma conta nova e ela nasce operador; escolha "Administrador" de propósito quando for o caso. Contas de antes deste campo existir ficam em branco para sempre (nunca são alteradas por trás) e por isso contam como administrador — ver `collections/papeis.ts`.
   */
  papel?: ('operador' | 'administrador') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'usuarios';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'representadas';
        value: number | Representada;
      } | null)
    | ({
        relationTo: 'pecas';
        value: number | Peca;
      } | null)
    | ({
        relationTo: 'arquivos3d';
        value: number | Arquivos3D;
      } | null)
    | ({
        relationTo: 'acabamentos';
        value: number | Acabamento;
      } | null)
    | ({
        relationTo: 'projetos';
        value: number | Projeto;
      } | null)
    | ({
        relationTo: 'paginas';
        value: number | Pagina;
      } | null)
    | ({
        relationTo: 'imagens';
        value: number | Imagen;
      } | null)
    | ({
        relationTo: 'logotipos';
        value: number | Logotipo;
      } | null)
    | ({
        relationTo: 'arquivos';
        value: number | Arquivo;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'usuarios';
        value: number | Usuario;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'usuarios';
    value: number | Usuario;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'usuarios';
    value: number | Usuario;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "representadas_select".
 */
export interface RepresentadasSelect<T extends boolean = true> {
  nome?: T;
  slug?: T;
  ordem?: T;
  resolve?: T;
  parte?: T;
  base?: T;
  fato?: T;
  logotipo?: T;
  imagem?: T;
  imagemLarga?: T;
  declaracoes?:
    | T
    | {
        rotulo?: T;
        valor?: T;
        id?: T;
      };
  designers?:
    | T
    | {
        nome?: T;
        colecoes?: T;
        nota?: T;
        id?: T;
      };
  colecoes?: T;
  vocabulario?:
    | T
    | {
        eixo?: T;
        grupos?:
          | T
          | {
              nome?: T;
              slug?: T;
              itens?:
                | T
                | {
                    nome?: T;
                    nota?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  catalogos?:
    | T
    | {
        titulo?: T;
        ano?: T;
        arquivo?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pecas_select".
 */
export interface PecasSelect<T extends boolean = true> {
  representada?: T;
  nome?: T;
  categoria?: T;
  foto?: T;
  ambiente?: T;
  materiais?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "arquivos3d_select".
 */
export interface Arquivos3DSelect<T extends boolean = true> {
  representada?: T;
  nome?: T;
  arquivo?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "acabamentos_select".
 */
export interface AcabamentosSelect<T extends boolean = true> {
  representada?: T;
  nome?: T;
  tipo?: T;
  amostra?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projetos_select".
 */
export interface ProjetosSelect<T extends boolean = true> {
  obra?: T;
  cidade?: T;
  uf?: T;
  ano?: T;
  marcas?: T;
  foto?: T;
  creditoArquiteto?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paginas_select".
 */
export interface PaginasSelect<T extends boolean = true> {
  slug?: T;
  titulo?: T;
  resumo?: T;
  composicao?:
    | T
    | {
        prosa?: T | BlocoDeProsaSelect<T>;
        caminhos?: T | BlocoDeCaminhosSelect<T>;
        ficha?: T | BlocoDeFichaSelect<T>;
        fecho?: T | BlocoDeFechoSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlocoDeProsa_select".
 */
export interface BlocoDeProsaSelect<T extends boolean = true> {
  titulo?: T;
  corpo?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlocoDeCaminhos_select".
 */
export interface BlocoDeCaminhosSelect<T extends boolean = true> {
  titulo?: T;
  itens?:
    | T
    | {
        rotulo?: T;
        apoio?: T;
        destino?: T;
        rota?: T;
        contexto?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlocoDeFicha_select".
 */
export interface BlocoDeFichaSelect<T extends boolean = true> {
  titulo?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlocoDeFecho_select".
 */
export interface BlocoDeFechoSelect<T extends boolean = true> {
  rotulo?: T;
  contexto?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imagens_select".
 */
export interface ImagensSelect<T extends boolean = true> {
  descricao?: T;
  mock?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logotipos_select".
 */
export interface LogotiposSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "arquivos_select".
 */
export interface ArquivosSelect<T extends boolean = true> {
  titulo?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  nome?: T;
  email?: T;
  cidade?: T;
  escritorio?: T;
  consentimentoMarketing?: T;
  origem?:
    | T
    | {
        pagina?: T;
        marca?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuarios_select".
 */
export interface UsuariosSelect<T extends boolean = true> {
  nome?: T;
  papel?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Os dados da própria Belmare: como falar com ela, quem ela é no registro e onde fica. Tudo aqui aparece no rodapé, e o rodapé está em todas as páginas do site — inclusive na de erro.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "empresa".
 */
export interface Empresa {
  id: number;
  /**
   * O número com DDD, como você o escreveria para alguém — (48) 99137-5030. Pode digitar com parênteses, espaço e traço. ⚠️ Enquanto este campo estiver vazio, o site não mostra botão de WhatsApp em página nenhuma: é melhor não oferecer o canal do que oferecer um link que abre e diz que o número não existe.
   */
  whatsapp?: string | null;
  /**
   * O endereço que recebe contato comercial, escrito por extenso. Ele aparece no rodapé de todas as páginas. Vazio, a linha do e-mail simplesmente não aparece.
   */
  email?: string | null;
  /**
   * Os telefones que aparecem no rodapé e na ficha de atendimento de /quem-somos, na ordem em que você quer que sejam vistos. Cada um vira um link que disca no celular do visitante.
   */
  telefones?:
    | {
        /**
         * Com DDD, escrito como você escreveria — (48) 3234-6004. O site mostra exatamente o que estiver aqui.
         */
        numero: string;
        id?: string | null;
      }[]
    | null;
  /**
   * O endereço completo do perfil — https://www.instagram.com/belmarerepresentacoes. Vazio, o link some do rodapé.
   */
  instagram?: string | null;
  /**
   * Como a empresa se apresenta hoje — "Belmare Representações". É o nome que acompanha o site quando alguém o compartilha.
   */
  nomeCompleto: string;
  /**
   * Como consta no registro — "Bello Mare Mercantil Ltda". Transcreva; não traduza para o cliente.
   */
  razaoSocial: string;
  /**
   * Os catorze dígitos. Pode digitar com ou sem pontuação — o site escreve no formato do cadastro.
   */
  cnpj: string;
  /**
   * O dia em que a empresa foi aberta, como consta no registro. ⚠️ Não existe campo de "anos de mercado" em lugar nenhum deste painel, e não deve passar a existir: o site conta os anos a partir desta data, sozinho, e vira a contagem no aniversário. Um número digitado ficaria errado a partir do aniversário seguinte sem ninguém perceber.
   */
  abertura: string;
  endereco?: {
    /**
     * "Rua Zanzibar do Nascimento Lins, 81".
     */
    logradouro?: string | null;
    bairro?: string | null;
    cidade?: string | null;
    /**
     * Duas letras — SC.
     */
    uf?: string | null;
    /**
     * "88.036-225" ou 88036225.
     */
    cep?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * O texto editável da página inicial. O título grande, o nome das duas portas e a lista de marcas não estão aqui: os dois primeiros são decisão de desenho e a lista o site monta sozinho a partir das representadas cadastradas.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  /**
   * O parágrafo logo abaixo de "O que cada uma das quatro fábricas faz." — o título conta as marcas sozinho, então não repita o número nele. Em branco, o parágrafo desaparece e a seção abre direto nas fotografias, e isso é um resultado válido: cada fábrica já mostra a própria linha logo abaixo. ⚠️ Não escreva benefício aqui. "Conforto" e "sombra" dizem o que o cliente sente; quem lê esta página especifica e revende, e lê o que a fábrica faz. E não conte interlocutores — "um interlocutor para as quatro" já foi recusado duas vezes. ⚠️ Se uma quinta fábrica entrar, esta frase é sua para reescrever: o título vira sozinho, este texto não.
   */
  galeria?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Todo o texto de /quem-somos, na ordem em que ele aparece na página. Título em branco volta para o texto padrão; parágrafo em branco faz o parágrafo desaparecer, nunca aparecer vazio. A ordem das seções é desenho da página e não se edita aqui.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quem-somos".
 */
export interface QuemSomos {
  id: number;
  /**
   * A primeira linha que o visitante lê. Diga em quem a Belmare atende e onde. ⚠️ Não repita o título da home ("Representação comercial de mobiliário de área externa."): quem chega aqui já leu aquilo duas rolagens atrás. Em branco, volta para o texto padrão.
   */
  titulo?: string | null;
  /**
   * Uma ou duas frases sobre o que a empresa é e há quanto tempo. ⚠️ Sem missão, valores ou superlativo. Marcadores disponíveis, e o site troca cada um pelo dado de hoje: {anos} = o tempo de casa, contado da data de abertura — 27 · {fabricas} = quantas fábricas estão publicadas, por extenso — quatro · {cidade} = a cidade da sede, como está no cadastro — Florianópolis · {estados} = o território por extenso — Paraná, Santa Catarina e Rio Grande do Sul · {quantosEstados} = quantos estados o território tem, por extenso — três. Não digite o número à mão: escrito à mão ele para de mudar.
   */
  apresentacao?: string | null;
  /**
   * Em branco, volta para o texto padrão.
   */
  atuacaoTitulo?: string | null;
  /**
   * Em uma ou duas frases, como a Belmare trabalha com a loja e com o escritório de arquitetura. ⚠️ Sem promessa de prazo, de exclusividade ou de condição comercial. Marcadores disponíveis, e o site troca cada um pelo dado de hoje: {anos} = o tempo de casa, contado da data de abertura — 27 · {fabricas} = quantas fábricas estão publicadas, por extenso — quatro · {cidade} = a cidade da sede, como está no cadastro — Florianópolis · {estados} = o território por extenso — Paraná, Santa Catarina e Rio Grande do Sul · {quantosEstados} = quantos estados o território tem, por extenso — três. Não digite o número à mão: escrito à mão ele para de mudar.
   */
  atuacao?: string | null;
  /**
   * A lista sob o parágrafo, uma linha por etapa do trabalho. ⚠️ Cada linha descreve o que a empresa FAZ, não o que o cliente ganha — "acompanha o pedido junto com a loja" é trabalho, "atendimento diferenciado" é autoelogio. Sem nenhuma etapa, a lista inteira desaparece e a seção fica só com o parágrafo.
   */
  atuacaoLinhas?:
    | {
        /**
         * Uma ou duas palavras, na coluna da esquerda — "Representação", "Especificação", "Pedido", "Pós-venda".
         */
        rotulo: string;
        /**
         * Marcadores disponíveis, e o site troca cada um pelo dado de hoje: {anos} = o tempo de casa, contado da data de abertura — 27 · {fabricas} = quantas fábricas estão publicadas, por extenso — quatro · {cidade} = a cidade da sede, como está no cadastro — Florianópolis · {estados} = o território por extenso — Paraná, Santa Catarina e Rio Grande do Sul · {quantosEstados} = quantos estados o território tem, por extenso — três. Não digite o número à mão: escrito à mão ele para de mudar.
         */
        texto: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Em branco, volta para o texto padrão.
   */
  acervoTitulo?: string | null;
  /**
   * A lista das fábricas é montada sozinha logo abaixo deste parágrafo, com o que está cadastrado em Representadas. ⚠️ Nada aqui pode descrever o contrato das fábricas — exclusividade é termo comercial de terceiro. Marcadores disponíveis, e o site troca cada um pelo dado de hoje: {anos} = o tempo de casa, contado da data de abertura — 27 · {fabricas} = quantas fábricas estão publicadas, por extenso — quatro · {cidade} = a cidade da sede, como está no cadastro — Florianópolis · {estados} = o território por extenso — Paraná, Santa Catarina e Rio Grande do Sul · {quantosEstados} = quantos estados o território tem, por extenso — três. Não digite o número à mão: escrito à mão ele para de mudar.
   */
  acervo?: string | null;
  /**
   * Em branco, volta para o texto padrão.
   */
  territorioTitulo?: string | null;
  /**
   * ⚠️ O mapa ao lado é a malha oficial do IBGE e desenha exatamente três estados; ele não se edita no painel. Escreva o território com {estados} e {quantosEstados}, nunca com os nomes digitados — é assim que a prosa não passa a dizer "quatro estados" ao lado de um desenho com três. Marcadores disponíveis, e o site troca cada um pelo dado de hoje: {anos} = o tempo de casa, contado da data de abertura — 27 · {fabricas} = quantas fábricas estão publicadas, por extenso — quatro · {cidade} = a cidade da sede, como está no cadastro — Florianópolis · {estados} = o território por extenso — Paraná, Santa Catarina e Rio Grande do Sul · {quantosEstados} = quantos estados o território tem, por extenso — três. Não digite o número à mão: escrito à mão ele para de mudar.
   */
  territorio?: string | null;
  /**
   * ⚠️ A seção inteira só aparece com três projetos publicados ou mais — com menos, nem o título nem o parágrafo vão ao ar. Em branco, volta para o texto padrão.
   */
  projetosTitulo?: string | null;
  /**
   * O que a lista de fotos abaixo mostra. ⚠️ Toda obra citada tem que existir e ter sido de fato entregue: as fotos e os créditos vêm de Projetos, e o que não existe fica ausente. Marcadores disponíveis, e o site troca cada um pelo dado de hoje: {anos} = o tempo de casa, contado da data de abertura — 27 · {fabricas} = quantas fábricas estão publicadas, por extenso — quatro · {cidade} = a cidade da sede, como está no cadastro — Florianópolis · {estados} = o território por extenso — Paraná, Santa Catarina e Rio Grande do Sul · {quantosEstados} = quantos estados o território tem, por extenso — três. Não digite o número à mão: escrito à mão ele para de mudar.
   */
  projetos?: string | null;
  /**
   * Em branco, volta para o texto padrão.
   */
  contatoTitulo?: string | null;
  /**
   * Diga o que acontece quando alguém chama. ⚠️ Nenhum e-mail de fábrica entra neste site, em lugar nenhum: um representante que se desintermedia do próprio funil está construindo o site do concorrente. Mas isso é regra de bastidor — não a explique ao visitante dentro do parágrafo. Marcadores disponíveis, e o site troca cada um pelo dado de hoje: {anos} = o tempo de casa, contado da data de abertura — 27 · {fabricas} = quantas fábricas estão publicadas, por extenso — quatro · {cidade} = a cidade da sede, como está no cadastro — Florianópolis · {estados} = o território por extenso — Paraná, Santa Catarina e Rio Grande do Sul · {quantosEstados} = quantos estados o território tem, por extenso — três. Não digite o número à mão: escrito à mão ele para de mudar.
   */
  contato?: string | null;
  /**
   * A linha em maiúsculas sob a foto larga do fecho. ⚠️ Ela existe porque a imagem é de banco e cai no lugar onde um arquiteto espera obra entregue — sem a legenda, a foto vira portfólio de trabalho que não foi feito. Em branco, volta para o texto padrão em vez de sumir; se a fotografia um dia for de uma obra real e creditada, a legenda muda aqui.
   */
  contatoLegenda?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * A fotografia de /representadas e as chamadas numeradas que apontam para os objetos dela. Suba a fotografia, arraste cada pino até o lugar e publique — nenhum número precisa ser calculado.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prancha".
 */
export interface Prancha {
  id: number;
  /**
   * A vista de conjunto que a prancha chaveia: uma área externa inteira com os objetos SEPARADOS no quadro, cada um com ar em volta para receber uma chamada. ⚠️ Numa cena em que o ombrelone cobre o sofá, duas chamadas apontam para o mesmo ponto e a prancha deixa de ser conferível. Ao trocar a fotografia, confira os pinos abaixo: eles continuam onde estavam, e o que estava embaixo deles mudou.
   */
  foto: number | Imagen;
  /**
   * Uma chamada por fábrica identificada na cena. A ordem aqui é a numeração do desenho e a ordem da legenda — 01, 02, 03… O número não se digita: ele é a posição na lista.
   */
  chamadas?:
    | {
        /**
         * A fábrica de onde vem esta parte da cena. O texto da chamada NÃO se escreve aqui: ele é a palavra que a representada já declara em "A mesma linha em uma palavra" — móvel, estrutura, estofado, sombra. Duas marcas que dividem a mesma função entram como duas chamadas apontando para o mesmo objeto.
         */
        representada: number | Representada;
        /**
         * 0 é a borda esquerda da fotografia, 100 a direita.
         */
        rotuloX: number;
        /**
         * 0 é o topo da fotografia, 100 o pé.
         */
        rotuloY: number;
        /**
         * Onde a linha encosta no objeto, não onde o número fica.
         */
        alvoX: number;
        /**
         * Idem, no eixo vertical.
         */
        alvoY: number;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * O download único de /arquivos-3d: as quatro fábricas, com acabamentos e tecidos, num arquivo só. É o ÚNICO arquivo do site que pede cadastro — os arquivos 3D avulsos baixam direto, sem formulário, porque a Casoca já os entrega de graça e cobrar cadastro por eles só afasta o arquiteto.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pacote-3d".
 */
export interface Pacote3D {
  id: number;
  /**
   * O pacote pronto, montado por você: os arquivos 3D das quatro fábricas mais as cartas de acabamento e tecido, num arquivo compactado. ⚠️ Ele NÃO se atualiza sozinho — um arquivo 3D novo entra na lista da página na hora, mas só entra no pacote quando você remontar e subir de novo. Em branco, a seção do pacote inteira desaparece da página, com o formulário junto: o site nunca pede cadastro em troca de um arquivo que não existe.
   */
  pacote?: (number | null) | Arquivo;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "empresa_select".
 */
export interface EmpresaSelect<T extends boolean = true> {
  whatsapp?: T;
  email?: T;
  telefones?:
    | T
    | {
        numero?: T;
        id?: T;
      };
  instagram?: T;
  nomeCompleto?: T;
  razaoSocial?: T;
  cnpj?: T;
  abertura?: T;
  endereco?:
    | T
    | {
        logradouro?: T;
        bairro?: T;
        cidade?: T;
        uf?: T;
        cep?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  galeria?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quem-somos_select".
 */
export interface QuemSomosSelect<T extends boolean = true> {
  titulo?: T;
  apresentacao?: T;
  atuacaoTitulo?: T;
  atuacao?: T;
  atuacaoLinhas?:
    | T
    | {
        rotulo?: T;
        texto?: T;
        id?: T;
      };
  acervoTitulo?: T;
  acervo?: T;
  territorioTitulo?: T;
  territorio?: T;
  projetosTitulo?: T;
  projetos?: T;
  contatoTitulo?: T;
  contato?: T;
  contatoLegenda?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prancha_select".
 */
export interface PranchaSelect<T extends boolean = true> {
  foto?: T;
  chamadas?:
    | T
    | {
        representada?: T;
        rotuloX?: T;
        rotuloY?: T;
        alvoX?: T;
        alvoY?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pacote-3d_select".
 */
export interface Pacote3DSelect<T extends boolean = true> {
  pacote?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}